config/routes.rb
Rails.application.routes.draw do

  get 'stories/demo' => 'stories#demo'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :stories do
    resources :sentences, only: [:create, :update]
  end

  root "welcome#index"



  devise_for :users, :controllers => { registrations: 'registrations' }

  post 'stories/:id/export' => 'stories#export', as: :story_export

  get '/download/:file.:filetype' => 'stories#download'

  delete '/download/:file.:filetype' => 'stories#delete_export'

  get 'stories/:share_url/share' => 'stories#share', as: :story_share




end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  has_many :children, class_name: "Sentence", foreign_key: "parent_id"

  belongs_to :parent, class_name: "Sentence"

  validates :depth, presence: true
  validates :story_id, presence: true
  validates :position, presence: true
end

app/models/story.rb
class Story < ActiveRecord::Base
  require 'export'
  include Export

  belongs_to :user
  has_many :sentences

  validates :name, presence: true
  before_create :generate_share_url

  def short_title
    if name.length > 40
      return name[0..39] + "..."
    else
      return name
    end
  end

  private

  def generate_share_url
    self.share_url = Digest::SHA1.hexdigest(rand(1_000_000).to_s)[0..6]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def verify_author
    unless current_user && current_user == @story.user
      redirect_to new_user_session_path and return true
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    stories_demo_path
  end


  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_story
  before_action :verify_author

  def create
    @sentence = @story.sentences.build(sentence_params)
    if @sentence.save
      render json: @sentence.to_json
    else
      render json: @sentence.errors.full_messages.to_json
    end
  end

  def update
    @sentence = Sentence.find(params[:id])

    if @sentence.update(sentence_params)
      render json: @sentence.to_json
    else
      render json: @sentence.errors.full_messages.to_json
    end
  end

  private

  def sentence_params
    params.require(:sentence).permit(:id, :depth, :position, :content, :parent_id)
  end

  def get_story
    @story = Story.find(params[:story_id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  require 'digest'
  before_action :authenticate_user!, except: [:share]
  before_action :get_story, only: [:show, :destroy, :export, :update]
  before_action :verify_author, only: [:show, :destroy, :export, :update]

  def index
    @stories = current_user.stories.all
  end

  def show
    @sentence = Sentence.new

    @user = current_user if current_user

    @shared = false
  end

  def share
    @user = current_user if current_user
    @story = Story.find_by(share_url: params[:share_url])
    @shared = true
    render :show
  end

  def new
    @story = current_user.stories.new
  end

  def create
    @story = current_user.stories.new(story_params)
    if @story.save
      redirect_to @story
    else
      render :new
    end
  end

  def update
    if @story.update(story_params)
      render json: @story.to_json
    else
      render json: @story.errors.full_messages.to_json
    end
  end

  def destroy
    @story.destroy
    redirect_to root_path
  end

  def export
    cookies['fileDownload'] = 'true'
    file_link = @story.export_story(params[:filetype])
    render json: { url: file_link }.to_json
  end


  def download
    file = File.open("tmp/#{params[:file]}.#{params[:filetype]}", 'r')
    mime_type = case params[:filetype]
                when 'rtf' then 'text/richtext; charset=UTF-8'
                when 'pdf' then 'application/pdf; charset=UTF-8'
                when 'md' then 'text/x-markdown; charset=UTF-8'
                end
    send_file file,
        :type => mime_type,
        :disposition => "attachment; filename=#{params[:file]}.#{params[:filetype]}"
  end

  def delete_export
    file = "tmp/#{params[:file]}.#{params[:filetype]}"
    File.delete(file) if File.exist?(file)
    respond_to do |format|
      format.json {render :json => "200".to_json}
    end
  end

  def demo
    @story = Story.new

    # render :demo, layout: false

  end

  private

  def story_params
    params.require(:story).permit(:name, :filetype)
  end

  def get_story
    @story = Story.find(params[:id])
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user
      render 'users/show'
    else
      @home = true
      render 'index'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
   def current_user
     @current_user ||= session[:user_id] && User.find_by_id(session[:user_id]) # Use find_by_id to get nil instead of an error if user doesn't exist
   end
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_controls
    if ( params['controller'] == 'stories' &&
       ( params['action'] == 'show' ||
	 params['action'] == 'share' || params['action'] == 'demo') )
      render :partial => 'stories/story_nav'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>three sentences <%= @story.name if @story %></title>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Lora|Varela+Round' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/favicon.ico">
    <link rel="icon" sizes="16x16 32x32 64x64" href="/favicon.ico">
    <link rel="icon" type="image/png" sizes="196x196" href="/favicon-196.png">
    <link rel="icon" type="image/png" sizes="160x160" href="/favicon-160.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96.png">
    <link rel="icon" type="image/png" sizes="64x64" href="/favicon-64.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon-152.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon-144.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon-120.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon-114.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon-76.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon-72.png">
    <link rel="apple-touch-icon" href="/favicon-57.png">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="/favicon-144.png">
    <meta name="msapplication-config" content="/browserconfig.xml">
</head>
<body class="<%= controller.controller_name %>">

<%= render :partial => 'shared/header' %>

<%= yield %>

</body>
</html>

app/views/shared/_header.html.erb
<nav>
  <div class="left">
    <%= link_to raw('<i class="fa fa-home"></i>'), root_path, class: 'button home round' %>
    <%= story_controls %>
    <h3 class="tag-line"><a href="/">three sentences</a></h3>
  </div>

  <div class="title">
    <h1 class="story-name" contenteditable='true'><%= @story.name if @story %></h1>
  </div>

  <div class="session">
  <% unless user_signed_in? %>
    <% unless @home %>
  <%= link_to "Sign Up", new_user_registration_path, class: 'button invert signup' %>
    <% end %>
  <%= link_to "Log In", new_user_session_path, class: 'button login' %>
  <% else %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'button logout' %>
  <% end %>
  </div>
</nav>

app/views/stories/_children.html.erb
<% sentence.children.each do |child| %>
<div class="child">
<p><%= child.id %>, <%= child.depth %>, <%= child.position %> - <%= child.content %><br></p><br><br>

  <% if child.children.count < 3 %>
    <%= form_for [@story, @sentence] do |f| -%>
      <%= f.hidden_field :parent_id, :value => child.id %>
      <%= f.hidden_field :depth, :value => child.depth + 1 %>
      <%= f.hidden_field :position, :value =>  child.children.count + 1%>
      <%= f.label :content, "Content" %>
      <%= f.text_field :content %>
      <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end -%>
  <% end %>

<% unless child.children.empty? %>
  <%= render partial: 'stories/children', locals: { sentence: child } %>
<% end %>
</div>
<% end %>

app/views/stories/_export.html.erb
<div class="modal-bg">
  <div class="absolute-center-export">
      <h3>Copy this link to share your work</h3>
      <%= text_field_tag 'share_url', "#{root_url}stories/#{@story.share_url}/share", disabled: true, class: 'sharebox' %><br>
      <hr>
      <h3>Export<h3>
      <%= form_tag("/stories/#{params[:id]}/export") do %>
        <div class="radio">
          <%= radio_button_tag(:filetype, "rtf", checked: true) %>
          <%= label_tag(:filetype_rtf, "RTF") %>
          <%= radio_button_tag(:filetype, "pdf") %>
          <%= label_tag(:filetype_pdf, "PDF") %>
          <%= radio_button_tag(:filetype, "md") %>
          <%= label_tag(:filetype_md, "Markdown") %>
          <%= submit_tag 'Export', data: { disable_with: "Exporting..." } %>
        </div>
        <%= link_to raw('<i class="fa fa-close"></i>'), '#', class: 'close' %>
      <% end %>
  </div>
</div>

app/views/stories/_help.html.erb
<div class="modal-bg-help">
  <div class="absolute-center-help">
      <h3>Help<h3>
      <hr>
      <%= link_to raw('<i class="fa fa-close"></i>'), '#', class: 'close-help' %>
      <h4>Keyboard Shortcuts</h4>

      <div class="shortcuts">
        <table>
          <tr>
            <td class="short-left"><span class="key">&#8594;</span></td>
            <td class="short-right">moves right one column</span></td>
          </tr>
          <tr>
            <td class="short-left"><span class="key">&#8592;</td>
            <td class="short-right">moves left one column</span></td>
          </tr>
          <tr>
            <td class="short-left"><span class="key">shift + &#8594;</td>
            <td class="short-right">moves to last column on right</span></td>
          </tr>
          <tr>
            <td class="short-left"><span class="key">shift + &#8592;</td>
            <td class="short-right">moves to first column</span></td>
          </tr>
          <tr>
            <td class="short-left"><span class="key">shift + option + (1-6)</td>
            <td class="short-right">moves to specified column number</span></td>
          </tr>
          <tr>
            <td class="short-left"><span class="key">shift + ctrl + N</td>
            <td class="short-right">night mode</span></td>
          </tr>
        </table>
      </div>
      <%= link_to "Take the Tour Again", stories_demo_path, class: 'button' %>
  </div>
</div>

app/views/stories/_list.html.erb
<div class="absolute-center-icons">
     <div id="profile">

     <h2><%= @user.username %>'s stories</h2>
     <li>
       <%= link_to 'New Story', new_story_path, class: 'button newstory' %>
     </li>

   <ol>

   <div class="grid">

   <% @user.stories.each do |story| %>

    <%= link_to story do %>
      <div class="grouping">
      <div class="col-1">
      <i class="my-icon"><i></i><i></i><i></i></i>
      <h4><%= story.sentences.size %></h4>
      <br>
      <h6><%= 'sentence'.pluralize(story.sentences.size) %><h6>
      <h5><%= story.name %></h5>
      <h5><%= link_to 'Share', story_share_path(story) %>

      </div>
      </div>
    <% end %>

   <% end %>

   </ol>
</div>

app/views/stories/_sentence.html.erb
<div class="sentence" id="<%= sentence.id %>">
  <p><%= sentence.content %></p>
</div>

app/views/stories/_story_nav.html.erb
<%= link_to raw('<i class="fa fa-question"></i>'), '', class: 'button help round' %>

<%= link_to raw('<i class="fa fa-share"></i>'), '', class: 'button export round' %>

app/views/stories/index.html.erb
<% if user_signed_in? %>
  <p> <%= current_user.username %></p>

  <% @stories.all.each do |story| %>
    <p><%= link_to story.name, story %></p>
  <% end %>

<% end %>

<%= link_to "New Story", new_story_path  %>

app/views/stories/new.html.erb
<div class="container">
  <div class="absolute-center">
    <div class="newstoryform">
      <h2>What's your story's title?</h2>
      <%= form_for @story do |f| -%>
        <%= f.text_field :name, placeholder: 'Title', :required => true %> <br>
        <%= f.submit "Submit", :disable_with => 'Submiting...' %>
      <% end -%>
   </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="controls">
  <span class="save-indicator"><i class="fa fa-check-circle"></i> saved</span>
</div>

<%= render 'stories/help' %>
<%= render 'stories/export' %>

<div id="frame">

  <div class="slidee">
    <div class="column" data-depth="0" id="column-0">
      <input type="text" class="sentence" data-id="" data-position="1" data-parent-id="" data-depth="0" placeholder="The Beginning"></input>
      <input type="text" class="sentence" id="two" data-id="" data-position="2" data-parent-id="" data-depth="0" placeholder="The Conflict"></input>
      <input class="sentence" id="three" data-id="" data-position="3" data-parent-id="" data-depth="0" placeholder="The Resolution"></input>
    </div>
  </div>
</div>

<div class="column" id="the-end" data-depth="6">
  <div class="end-message">
    <i class="fa fa-book fa-5x"></i>
    <h3>You&#39;re ready to go write your story!<h3>
    <%= link_to "Export", root_path, class: 'button export end' %>
  </div>
</div>

<script type="text/template" class="template" id="column-template">
  <a href="#column-{{ depth }}" class='arrow'><i class="fa fa-chevron-right arrow"></i></a>
  <div class="column" data-depth="{{ depth }}" id="column-{{ depth }}">
</script>

<script type="text/template" class="template" id="sentence-template">
<input type="text" class="sentence" data-id="{{ sentence_id }}" data-position="{{ position }}" data-depth="{{ depth }}" data-parent-id="{{ parent_id }}"></input>
</script>

<script type="text/template" class="template" id="cue-template">
  <h3 class="cue" data-parent-position="{{ parent_position }}"><span class="cue cue_arrow"><i class="fa fa-angle-right fa-lg"></i></span><span class="cue-text">{{ cue }}</span></h3>
</script>

<script>
  var shared = <%= @shared %>;
  var story = new Story(<%= raw json_escape(@story.to_json) %>);
  var sentencesJson = [];
  <% if @story.sentences %>
  sentencesJson = <%= raw json_escape(@story.sentences.order(:position).to_json) %>
  <% end %>
</script>

app/views/users/show.html.erb
<div class="container">
  <div class="absolute-center-icons">
  <div id="profile">

    <h2><%= current_user.username %>'s stories</h2>

    <%= link_to raw('<i class="fa fa-pencil-square-o"></i> New Story'), new_story_path, class: 'button newstory' %>


    <div >
      <ul class="story-list">
      <% current_user.stories.each do |story| %>
        <li class="story-link">
        <%= link_to story do %>
          <i class="fa fa-book fa-2x"></i><%= story.short_title %>
        <% end %>
        </li>
      <% end %>
      </ul>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
    <div class="absolute-center">
      <h1 id="brand">three sentences</h1>
      <p id="tagline">If you can write three sentences,<br> you can write a story.</p>
     <%= link_to "Sign Up", new_user_registration_path, class: 'button invert signup' %>
  </div>
</div>